### ISSUE TITLE
Namespace Specific Serializer Settings

### ISSUE THREAD

**Issue by turecross321** [PlanetBunkum/Bunkum#27]
It should be possible to modify the JSON serializer settings for specific namespaces. This way you can, for example, make the server serialize API responses one way and game responses a different way.

**Comment by jvyden** [comment]
Thinking of having the serialization settings be a part of the `EndpointGroup` class to avoid using reflection. You'd have to manually update every usage of `EndpointGroup` for the serializers you want to use, but it's better than constantly doing reflection stuff every request - more than we already do.

**Comment by jvyden** [comment]
This issue is no longer relevant as you can now define your own serializers in Bunkum. Next release will include a function to remove existing serializers so you can properly override them.
