### ISSUE TITLE
Bunkum.ProfanityFilter can be bypassed by not using any spaces

### ISSUE THREAD

**Issue by turecross321** [PlanetBunkum/Bunkum#41]
The profanity system currently appears to split words by spaces, and check if any of the words contain profanity, and this is pretty easily circumvented.

A user can simply decide to not use spaces in their request, and nothing will be filtered.

![image.png](https://github.com/LittleBigRefresh/Bunkum.ProfanityFilter/assets/51852312/d925d29c-d2ec-4268-8416-880a2137058e)

 
Splitting the string by spaces is obviously to avoid false positives which is a problem that the other method: checking if a string contains profanity at all, does a lot. But I think that it's, in some situations, important that no profanity gets through - even though some false positives will appear.

I therefore suggest implementing an additional setting in the setup, or maybe a parameter in the actual profanity checking, that makes the filter check if the whole string contains any profanity, or if it should split the string by spaces first.

**Comment by jvyden** [comment]
Yeah, this is going to be a recurring issue, I feel. There are pros and 
cons to fixing this - either path you end up with problems. On one side, 
you're left dealing with the Scunthorpe problem, the other you're 
micromanaging a allow/deny list of swears.

I'm planning to implement a `ProfanityFilterSettings` object that can be 
added to the service's constructor so you can better manage this sort of 
thing. I may even expose a class so a JSON config can easily be added so 
instance maintainers can tweak it to their liking.

There's no universal solution here, unfortunately. I'll take a look at 
the library we're using to see if there are any good workarounds that 
can be put in-place behind a config flag.

**Comment by jvyden** [comment]
No longer in scope.
